export type DetentionFacility = {
  name: string;
  fieldOffice: string;
  address: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  phone: string;
  addressFull: string;
  detailUrl: string;
  latitude: number | null;
  longitude: number | null;
};

export const DETENTION_FACILITIES = [
  {
    "name": "Naval Station Guantanamo Bay (JTF Camp Six and Migrant Ops Center Main A)",
    "fieldOffice": "Miami Field Office",
    "address": "",
    "city": "",
    "state": "",
    "postalCode": "",
    "country": "",
    "phone": "",
    "addressFull": "",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/naval-station-guantanamo-bay",
    "latitude": 38.7945952,
    "longitude": -106.5348379
  },
  {
    "name": "Anchorage Correctional Complex",
    "fieldOffice": "Seattle Field Office",
    "address": "1400 E Fourth Ave",
    "city": "Anchorage",
    "state": "AK",
    "postalCode": "99501",
    "country": "United States",
    "phone": "",
    "addressFull": "1400 E Fourth Ave Anchorage, AK 99501 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/anchorage-correctional-complex",
    "latitude": 61.2185041,
    "longitude": -149.8573539
  },
  {
    "name": "Eloy Detention Center",
    "fieldOffice": "Phoenix Field Office",
    "address": "1705 E Hanna Road",
    "city": "Eloy",
    "state": "AZ",
    "postalCode": "85131",
    "country": "United States",
    "phone": "",
    "addressFull": "1705 E Hanna Road Eloy, AZ 85131 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/eloy-detention-center",
    "latitude": 32.8176183,
    "longitude": -111.5200907
  },
  {
    "name": "Central Arizona Florence Correctional Center",
    "fieldOffice": "Phoenix Field Office",
    "address": "1100 Bowling Road",
    "city": "Florence",
    "state": "AZ",
    "postalCode": "85132",
    "country": "United States",
    "phone": "",
    "addressFull": "1100 Bowling Road Florence, AZ 85132 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/florence-correctional-center",
    "latitude": 33.0433427,
    "longitude": -111.3720644
  },
  {
    "name": "Florence Service Processing Center",
    "fieldOffice": "Phoenix Field Office",
    "address": "3250 N. Pinal Parkway",
    "city": "Florence",
    "state": "AZ",
    "postalCode": "85132",
    "country": "United States",
    "phone": "",
    "addressFull": "3250 N. Pinal Parkway Florence, AZ 85132 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/florence-spc",
    "latitude": 33.0639503,
    "longitude": -111.3794387
  },
  {
    "name": "San Luis Regional Detention Center",
    "fieldOffice": "San Diego Field Office",
    "address": "406 North Avenue D",
    "city": "San Luis",
    "state": "AZ",
    "postalCode": "85349",
    "country": "United States",
    "phone": "",
    "addressFull": "406 North Avenue D San Luis, AZ 85349 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/san-luis-regional-detention-center",
    "latitude": 32.4828449,
    "longitude": -114.6835588
  },
  {
    "name": "Adelanto ICE Processing Center",
    "fieldOffice": "Los Angeles Field Office",
    "address": "Adelanto East 10400 Rancho Road | Adelanto West 10250 Rancho Road",
    "city": "Adelanto",
    "state": "CA",
    "postalCode": "92301",
    "country": "United States",
    "phone": "",
    "addressFull": "Adelanto East 10400 Rancho Road | Adelanto West 10250 Rancho Road Adelanto, CA 92301 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/adelanto-ice-processing-center",
    "latitude": 34.5591013,
    "longitude": -117.4414952
  },
  {
    "name": "Desert View Annex",
    "fieldOffice": "Los Angeles Field Office",
    "address": "10450 Rancho Road",
    "city": "Adelanto",
    "state": "CA",
    "postalCode": "92301",
    "country": "United States",
    "phone": "",
    "addressFull": "10450 Rancho Road Adelanto, CA 92301 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/desert-view-annex",
    "latitude": 34.5588215,
    "longitude": -117.4372847
  },
  {
    "name": "Mesa Verde ICE Processing Center",
    "fieldOffice": "San Francisco Field Office",
    "address": "425 Golden State Avenue",
    "city": "Bakersfield",
    "state": "CA",
    "postalCode": "93301",
    "country": "United States",
    "phone": "",
    "addressFull": "425 Golden State Avenue Bakersfield, CA 93301 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/mesa-verde-ice-processing-facility",
    "latitude": 35.3799739,
    "longitude": -119.0064452
  },
  {
    "name": "Imperial Regional Detention Facility",
    "fieldOffice": "San Diego Field Office",
    "address": "1572 Gateway Road",
    "city": "Calexico",
    "state": "CA",
    "postalCode": "92231",
    "country": "United States",
    "phone": "",
    "addressFull": "1572 Gateway Road Calexico, CA 92231 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/imperial-regional-detention-facility",
    "latitude": 32.6901156,
    "longitude": -115.3975363
  },
  {
    "name": "California City Detention Facility",
    "fieldOffice": "San Francisco Field Office",
    "address": "22844 Virginia Boulevard",
    "city": "California City",
    "state": "CA",
    "postalCode": "93505",
    "country": "United States",
    "phone": "",
    "addressFull": "22844 Virginia Boulevard California City, CA 93505 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/california-city-detention-facility",
    "latitude": 35.1517183,
    "longitude": -117.858652
  },
  {
    "name": "Golden State Annex",
    "fieldOffice": "San Francisco Field Office",
    "address": "611 Frontage Road",
    "city": "McFarland",
    "state": "CA",
    "postalCode": "93250",
    "country": "United States",
    "phone": "",
    "addressFull": "611 Frontage Road McFarland, CA 93250 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/golden-state-annex",
    "latitude": 35.6697644,
    "longitude": -119.2278172
  },
  {
    "name": "Otay Mesa Detention Center",
    "fieldOffice": "San Diego Field Office",
    "address": "7488 Calzada de la Fuente",
    "city": "San Diego",
    "state": "CA",
    "postalCode": "92154",
    "country": "United States",
    "phone": "",
    "addressFull": "7488 Calzada de la Fuente San Diego, CA 92154 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/otay-mesa-detention-center",
    "latitude": 32.5750242,
    "longitude": -116.9147637
  },
  {
    "name": "Denver Contract Detention Facility (Aurora)",
    "fieldOffice": "Denver Field Office",
    "address": "3130 North Oakland Street",
    "city": "Aurora",
    "state": "CO",
    "postalCode": "80010",
    "country": "United States",
    "phone": "",
    "addressFull": "3130 North Oakland Street Aurora, CO 80010 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/aurora-contract-detention-facility",
    "latitude": 39.76134709999999,
    "longitude": -104.8490165
  },
  {
    "name": "Baker County Detention Center",
    "fieldOffice": "Miami Field Office",
    "address": "1 Sheriff's Office Drive",
    "city": "MacClenny",
    "state": "FL",
    "postalCode": "32063",
    "country": "United States",
    "phone": "",
    "addressFull": "1 Sheriff's Office Drive MacClenny, FL 32063 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/baker-county-facility",
    "latitude": 30.29596799999999,
    "longitude": -82.1217298
  },
  {
    "name": "FDC Miami",
    "fieldOffice": "Miami Field Office",
    "address": "33 NE 4th Street",
    "city": "Miami",
    "state": "FL",
    "postalCode": "33132",
    "country": "United States",
    "phone": "",
    "addressFull": "33 NE 4th Street Miami, FL 33132 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/fdc-miami",
    "latitude": 25.7785364,
    "longitude": -80.1932264
  },
  {
    "name": "Krome North Service Processing Center",
    "fieldOffice": "Miami Field Office",
    "address": "18201 SW 12th Street",
    "city": "Miami",
    "state": "FL",
    "postalCode": "33194",
    "country": "United States",
    "phone": "",
    "addressFull": "18201 SW 12th Street Miami, FL 33194 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/krome-north-service-processing-center",
    "latitude": 25.7543477,
    "longitude": -80.4891143
  },
  {
    "name": "Glades County Detention Center",
    "fieldOffice": "Miami Field Office",
    "address": "1297 East SR 78",
    "city": "Moore Haven",
    "state": "FL",
    "postalCode": "33471",
    "country": "United States",
    "phone": "",
    "addressFull": "1297 East SR 78 Moore Haven, FL 33471 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/glades-county-detention-center",
    "latitude": 26.8386472,
    "longitude": -81.1239104
  },
  {
    "name": "Broward Transitional Center",
    "fieldOffice": "Miami Field Office",
    "address": "3900 N. Powerline Road",
    "city": "Pompano Beach",
    "state": "FL",
    "postalCode": "33073",
    "country": "United States",
    "phone": "",
    "addressFull": "3900 N. Powerline Road Pompano Beach, FL 33073 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/broward-transitional-center",
    "latitude": 26.2777097,
    "longitude": -80.1521559
  },
  {
    "name": "FCI Atlanta",
    "fieldOffice": "Atlanta Field Office",
    "address": "601 McDonough Blvd SE",
    "city": "Atlanta",
    "state": "GA",
    "postalCode": "30315",
    "country": "United States",
    "phone": "",
    "addressFull": "601 McDonough Blvd SE Atlanta, GA 30315 United States",
    "detailUrl": "https://www.ice.gov/detention-facilities/fci-atlanta",
    "latitude": 33.7116427,
    "longitude": -84.3686625
  },
  {
    "name": "Folkston D Ray ICE Processing Center",
    "fieldOffice": "Atlanta Field Office",
    "address": "3262 Hwy 252E",
    "city": "Folkston",
    "state": "GA",
    "postalCode": "31537",
    "country": "United States",
    "phone": "",
    "addressFull": "3262 Hwy 252E Folkston, GA 31537 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/folkston-d-ray-ice-processing-center",
    "latitude": 30.8305102,
    "longitude": -82.0098375
  },
  {
    "name": "Folkston ICE Processing Center (Annex)",
    "fieldOffice": "Atlanta Field Office",
    "address": "3424 Hwy 252 E",
    "city": "Folkston",
    "state": "GA",
    "postalCode": "31537",
    "country": "United States",
    "phone": "",
    "addressFull": "3424 Hwy 252 E Folkston, GA 31537 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/folkston-ice-processing-center-annex",
    "latitude": 30.8749079,
    "longitude": -81.9806924
  },
  {
    "name": "Folkston ICE Processing Center (Main)",
    "fieldOffice": "Atlanta Field Office",
    "address": "3026 Hwy 252 East",
    "city": "Folkston",
    "state": "GA",
    "postalCode": "31537",
    "country": "United States",
    "phone": "",
    "addressFull": "3026 Hwy 252 East Folkston, GA 31537 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/folkston-ice-processing-center-main",
    "latitude": 30.8763257,
    "longitude": -81.97801609999999
  },
  {
    "name": "Stewart Detention Center",
    "fieldOffice": "Atlanta Field Office",
    "address": "146 CCA Road",
    "city": "Lumpkin",
    "state": "GA",
    "postalCode": "31815",
    "country": "United States",
    "phone": "",
    "addressFull": "146 CCA Road Lumpkin, GA 31815 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/stewart-detention-center",
    "latitude": 32.0365622,
    "longitude": -84.7713749
  },
  {
    "name": "Guam Department of Corrections, Hagatna Detention Facility",
    "fieldOffice": "San Francisco Field Office",
    "address": "203 Aspinall Avenue",
    "city": "Hagatna",
    "state": "GU",
    "postalCode": "96910",
    "country": "United States",
    "phone": "",
    "addressFull": "203 Aspinall Avenue Hagatna, GU 96910 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/guam-department-corrections-hagatna-detention-facility",
    "latitude": 13.474307,
    "longitude": 144.7505229
  },
  {
    "name": "Federal Detention Center, Honolulu (FDC Honolulu)",
    "fieldOffice": "San Francisco Field Office",
    "address": "351 Elliott Street",
    "city": "Honolulu",
    "state": "HI",
    "postalCode": "96819",
    "country": "United States",
    "phone": "",
    "addressFull": "351 Elliott Street Honolulu, HI 96819 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/federal-detention-center-honolulu-fdc-honolulu",
    "latitude": 21.3338725,
    "longitude": -157.9279267
  },
  {
    "name": "Pottawattamie County Jail",
    "fieldOffice": "St. Paul Field Office",
    "address": "1400 Big Lake Road",
    "city": "Council Bluffs",
    "state": "IA",
    "postalCode": "51501",
    "country": "United States",
    "phone": "",
    "addressFull": "1400 Big Lake Road Council Bluffs, IA 51501 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/pottawattamie-county-jail",
    "latitude": 41.2842697,
    "longitude": -95.8653913
  },
  {
    "name": "Polk County Jail",
    "fieldOffice": "St. Paul Field Office",
    "address": "1985 NE 51st Place",
    "city": "Des Moines",
    "state": "IA",
    "postalCode": "50313",
    "country": "United States",
    "phone": "",
    "addressFull": "1985 NE 51st Place Des Moines, IA 50313 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/polk-county-jail",
    "latitude": 41.6534852,
    "longitude": -93.587758
  },
  {
    "name": "Elmore County Detention Center (Elmore County Jail)",
    "fieldOffice": "Salt Lake City Field Office",
    "address": "2255 East 8th North",
    "city": "Mountain Home",
    "state": "ID",
    "postalCode": "83647",
    "country": "United States",
    "phone": "",
    "addressFull": "2255 East 8th North Mountain Home, ID 83647 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/elmore-county-detention-center-elmore-county-jail",
    "latitude": 43.1368404,
    "longitude": -115.6731309
  },
  {
    "name": "Clay County Jail",
    "fieldOffice": "Chicago Field Office",
    "address": "611 East Jackson Street",
    "city": "Brazil",
    "state": "IN",
    "postalCode": "47834",
    "country": "United States",
    "phone": "",
    "addressFull": "611 East Jackson Street Brazil, IN 47834 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/clay-county-jail",
    "latitude": 39.5237009,
    "longitude": -87.1190405
  },
  {
    "name": "Miami Correctional Facility (MCF)",
    "fieldOffice": "Chicago Field Office",
    "address": "3038 West 850S",
    "city": "Bunker Hill",
    "state": "IN",
    "postalCode": "46914",
    "country": "United States",
    "phone": "",
    "addressFull": "3038 West 850S Bunker Hill, IN 46914 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/miami-correctional-facility-mcf",
    "latitude": 40.644835,
    "longitude": -86.13349339999999
  },
  {
    "name": "Clinton County Sheriff's Office",
    "fieldOffice": "Chicago Field Office",
    "address": "301 E Walnut Street",
    "city": "Frankfort",
    "state": "IN",
    "postalCode": "46041",
    "country": "United States",
    "phone": "",
    "addressFull": "301 E Walnut Street Frankfort, IN 46041 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/clinton-county-so",
    "latitude": 40.2792086,
    "longitude": -86.50877799999999
  },
  {
    "name": "Clark County Jail",
    "fieldOffice": "Chicago Field Office",
    "address": "501 E Court Avenue",
    "city": "Jeffersonville",
    "state": "IN",
    "postalCode": "47130",
    "country": "United States",
    "phone": "",
    "addressFull": "501 E Court Avenue Jeffersonville, IN 47130 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/clark-county-jail",
    "latitude": 38.277738,
    "longitude": -85.73775429999999
  },
  {
    "name": "Chase County Jail",
    "fieldOffice": "Chicago Field Office",
    "address": "301 South Walnut",
    "city": "Cottonwood Falls",
    "state": "KS",
    "postalCode": "66845",
    "country": "United States",
    "phone": "",
    "addressFull": "301 South Walnut Cottonwood Falls, KS 66845 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/chase-county-jail",
    "latitude": 38.3678625,
    "longitude": -96.5386875
  },
  {
    "name": "FCI Leavenworth",
    "fieldOffice": "Chicago Field Office",
    "address": "1300 Metropolitan",
    "city": "Leavenworth",
    "state": "KS",
    "postalCode": "66048",
    "country": "United States",
    "phone": "",
    "addressFull": "1300 Metropolitan Leavenworth, KS 66048 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/fci-leavenworth",
    "latitude": 39.3299481,
    "longitude": -94.93634980000002
  },
  {
    "name": "Boone County Jail",
    "fieldOffice": "Chicago Field Office",
    "address": "3020 Conrad Lane",
    "city": "Burlington",
    "state": "KY",
    "postalCode": "41005",
    "country": "United States",
    "phone": "",
    "addressFull": "3020 Conrad Lane Burlington, KY 41005 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/boone-county-jail",
    "latitude": 39.0365031,
    "longitude": -84.7283616
  },
  {
    "name": "Kenton County Detention Center",
    "fieldOffice": "Chicago Field Office",
    "address": "3000 Decker Crane Lane",
    "city": "Covington",
    "state": "KY",
    "postalCode": "41017",
    "country": "United States",
    "phone": "",
    "addressFull": "3000 Decker Crane Lane Covington, KY 41017 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/kenton-county-detention-center",
    "latitude": 39.0024275,
    "longitude": -84.53061249999999
  },
  {
    "name": "Christian County Jail",
    "fieldOffice": "Chicago Field Office",
    "address": "410 West 7th Street",
    "city": "Hopkinsville",
    "state": "KY",
    "postalCode": "42240",
    "country": "United States",
    "phone": "",
    "addressFull": "410 West 7th Street Hopkinsville, KY 42240 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/christian-county-jail",
    "latitude": 36.8682675,
    "longitude": -87.490437
  },
  {
    "name": "Oldham County Detention Center",
    "fieldOffice": "Chicago Field Office",
    "address": "3405 West Highway 146",
    "city": "LaGrange",
    "state": "KY",
    "postalCode": "40031",
    "country": "United States",
    "phone": "(502) 222-3500",
    "addressFull": "3405 West Highway 146 LaGrange, KY 40031 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/oldham-county-detention-center",
    "latitude": 38.38929359999999,
    "longitude": -85.4237673
  },
  {
    "name": "Grayson County Detention Center",
    "fieldOffice": "Chicago Field Office",
    "address": "320 Shaw Station Road",
    "city": "Leachfield",
    "state": "KY",
    "postalCode": "42754",
    "country": "United States",
    "phone": "",
    "addressFull": "320 Shaw Station Road Leachfield, KY 42754 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/grayson-county-detention-center",
    "latitude": 37.4890253,
    "longitude": -86.27049819999999
  },
  {
    "name": "Hopkins County Jail",
    "fieldOffice": "Chicago Field Office",
    "address": "2250 Laffoon Trl",
    "city": "Madisonville",
    "state": "KY",
    "postalCode": "42431",
    "country": "United States",
    "phone": "",
    "addressFull": "2250 Laffoon Trl Madisonville, KY 42431 United States",
    "detailUrl": "https://www.ice.gov/detention-facilities/hopkins-county",
    "latitude": 37.3377164,
    "longitude": -87.54017809999999
  },
  {
    "name": "Campbell County Detention Center",
    "fieldOffice": "Chicago Field Office",
    "address": "601 Central Avenue",
    "city": "Newport",
    "state": "KY",
    "postalCode": "41071",
    "country": "United States",
    "phone": "(859) 431-4611",
    "addressFull": "601 Central Avenue Newport, KY 41071 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/campbell-county-detention-center",
    "latitude": 39.08908419999999,
    "longitude": -84.4963222
  },
  {
    "name": "Daviess County Detention Center",
    "fieldOffice": "Chicago Field Office",
    "address": "3337 Highway 144",
    "city": "Owensboro",
    "state": "KY",
    "postalCode": "42303",
    "country": "United States",
    "phone": "",
    "addressFull": "3337 Highway 144 Owensboro, KY 42303 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/daviess-county-detention-center",
    "latitude": 37.7871208,
    "longitude": -87.0702975
  },
  {
    "name": "Louisiana ICE Processing Center",
    "fieldOffice": "New Orleans Field Office",
    "address": "17544 Tunica Trace",
    "city": "Angola",
    "state": "LA",
    "postalCode": "70712",
    "country": "United States",
    "phone": "",
    "addressFull": "17544 Tunica Trace Angola, LA 70712 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/louisiana-ice-processing-center",
    "latitude": 30.9406745,
    "longitude": -91.5683806
  },
  {
    "name": "South Louisiana ICE Processing Center",
    "fieldOffice": "New Orleans Field Office",
    "address": "3843 Stagg Ave",
    "city": "Basile",
    "state": "LA",
    "postalCode": "70515",
    "country": "United States",
    "phone": "",
    "addressFull": "3843 Stagg Ave Basile, LA 70515 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/south-louisiana-ice-processing-center",
    "latitude": 30.4870681,
    "longitude": -92.581813
  },
  {
    "name": "River Correctional Center",
    "fieldOffice": "New Orleans Field Office",
    "address": "26362 Highway 15",
    "city": "Ferriday",
    "state": "LA",
    "postalCode": "71334",
    "country": "United States",
    "phone": "",
    "addressFull": "26362 Highway 15 Ferriday, LA 71334 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/river-correctional-center",
    "latitude": 31.5971028,
    "longitude": -91.5580974
  },
  {
    "name": "Central Louisiana ICE Processing Center",
    "fieldOffice": "New Orleans Field Office",
    "address": "830 Pine Hill Road",
    "city": "Jena",
    "state": "LA",
    "postalCode": "71342",
    "country": "United States",
    "phone": "",
    "addressFull": "830 Pine Hill Road Jena, LA 71342 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/central-louisiana-ipc",
    "latitude": 31.7089427,
    "longitude": -92.1505809
  },
  {
    "name": "Jackson Parish Correctional Center",
    "fieldOffice": "New Orleans Field Office",
    "address": "287 Industrial Drive",
    "city": "Jonesboro",
    "state": "LA",
    "postalCode": "71251",
    "country": "United States",
    "phone": "",
    "addressFull": "287 Industrial Drive Jonesboro, LA 71251 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/jackson-parish-correctional-center",
    "latitude": 32.215231,
    "longitude": -92.7158968
  },
  {
    "name": "Richwood Correctional Center",
    "fieldOffice": "New Orleans Field Office",
    "address": "180 Pine Bayou Circle",
    "city": "Monroe",
    "state": "LA",
    "postalCode": "71202",
    "country": "United States",
    "phone": "",
    "addressFull": "180 Pine Bayou Circle Monroe, LA 71202 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/richwood-correctional-center",
    "latitude": 32.4568901,
    "longitude": -92.0784706
  },
  {
    "name": "Allen Parish Public Safety Complex",
    "fieldOffice": "New Orleans Field Office",
    "address": "7340 Highway 26 W",
    "city": "Oberlin",
    "state": "LA",
    "postalCode": "70655",
    "country": "United States",
    "phone": "",
    "addressFull": "7340 Highway 26 W Oberlin, LA 70655 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/allen-parish-public-safety-complex",
    "latitude": 30.624485,
    "longitude": -92.783878
  },
  {
    "name": "Pine Prairie ICE Processing Center",
    "fieldOffice": "New Orleans Field Office",
    "address": "1133 Hampton Dupre Road",
    "city": "Pine Prairie",
    "state": "LA",
    "postalCode": "70576",
    "country": "United States",
    "phone": "",
    "addressFull": "1133 Hampton Dupre Road Pine Prairie, LA 70576 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/pine-prairie-ice-processing-center",
    "latitude": 30.7886095,
    "longitude": -92.42351459999999
  },
  {
    "name": "Winn Correctional Center",
    "fieldOffice": "New Orleans Field Office",
    "address": "560 Gum Springs Road",
    "city": "Winnfield",
    "state": "LA",
    "postalCode": "71483",
    "country": "United States",
    "phone": "",
    "addressFull": "560 Gum Springs Road Winnfield, LA 71483 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/winn-correctional-center",
    "latitude": 31.8389273,
    "longitude": -92.7903075
  },
  {
    "name": "Plymouth County Correctional Facility",
    "fieldOffice": "Boston Field Office",
    "address": "26 Long Pond Road",
    "city": "Plymouth",
    "state": "MA",
    "postalCode": "02360",
    "country": "United States",
    "phone": "",
    "addressFull": "26 Long Pond Road Plymouth, MA 02360 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/plymouth-county-correctional-facility",
    "latitude": 41.9313647,
    "longitude": -70.6510495
  },
  {
    "name": "Cumberland County Jail",
    "fieldOffice": "Boston Field Office",
    "address": "50 County Way",
    "city": "Portland",
    "state": "ME",
    "postalCode": "04102",
    "country": "United States",
    "phone": "(207) 774-5939",
    "addressFull": "50 County Way Portland, ME 04102 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/cumberland-county-jail",
    "latitude": 43.6513147,
    "longitude": -70.28180789999999
  },
  {
    "name": "North Lake Processing Center",
    "fieldOffice": "Detroit Field Office",
    "address": "1805 W 32nd Street",
    "city": "Baldwin",
    "state": "MI",
    "postalCode": "49304",
    "country": "United States",
    "phone": "",
    "addressFull": "1805 W 32nd Street Baldwin, MI 49304 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/north-lake-processing-center",
    "latitude": 43.9284879,
    "longitude": -85.83946130000001
  },
  {
    "name": "Calhoun County Correctional Center",
    "fieldOffice": "Detroit Field Office",
    "address": "185 E. Michigan Street",
    "city": "Battle Creek",
    "state": "MI",
    "postalCode": "49014",
    "country": "United States",
    "phone": "",
    "addressFull": "185 E. Michigan Street Battle Creek, MI 49014 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/calhoun-county-correctional-center",
    "latitude": 42.3166565,
    "longitude": -85.1757947
  },
  {
    "name": "Monroe County Jail",
    "fieldOffice": "Detroit Field Office",
    "address": "7000 East Dunbar Road",
    "city": "Monroe",
    "state": "MI",
    "postalCode": "48161",
    "country": "United States",
    "phone": "",
    "addressFull": "7000 East Dunbar Road Monroe, MI 48161 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/monroe-county-jail",
    "latitude": 41.89553069999999,
    "longitude": -83.39339439999999
  },
  {
    "name": "St. Clair County Jail",
    "fieldOffice": "Detroit Field Office",
    "address": "1170 Michigan Road",
    "city": "Port Huron",
    "state": "MI",
    "postalCode": "48060",
    "country": "United States",
    "phone": "",
    "addressFull": "1170 Michigan Road Port Huron, MI 48060 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/st-clair-county-jail",
    "latitude": 42.94231130000001,
    "longitude": -82.47947909999999
  },
  {
    "name": "Chippewa County Correctional Facility",
    "fieldOffice": "Detroit Field Office",
    "address": "325 Court Street",
    "city": "Sault Ste. Marie",
    "state": "MI",
    "postalCode": "49783",
    "country": "United States",
    "phone": "",
    "addressFull": "325 Court Street Sault Ste. Marie, MI 49783 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/chippewa-county-correctional-facility",
    "latitude": 46.4973719,
    "longitude": -84.3455596
  },
  {
    "name": "Freeborn County Jail Services",
    "fieldOffice": "St. Paul Field Office",
    "address": "411 S. Broadway Avenue",
    "city": "Albert Lea",
    "state": "MN",
    "postalCode": "56007",
    "country": "United States",
    "phone": "",
    "addressFull": "411 S. Broadway Avenue Albert Lea, MN 56007 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/freeborn-county-jail-services",
    "latitude": 43.6459816,
    "longitude": -93.3681003
  },
  {
    "name": "Sherburne County Jail Services",
    "fieldOffice": "St. Paul Field Office",
    "address": "13880 Business Center Drive NW",
    "city": "Elk River",
    "state": "MN",
    "postalCode": "55330",
    "country": "United States",
    "phone": "",
    "addressFull": "13880 Business Center Drive NW Elk River, MN 55330 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/sherburne-county-jail-services",
    "latitude": 45.304588,
    "longitude": -93.61912060000002
  },
  {
    "name": "Kandiyohi County Jail",
    "fieldOffice": "St. Paul Field Office",
    "address": "2201 23rd St. NE",
    "city": "Willmar",
    "state": "MN",
    "postalCode": "56201",
    "country": "United States",
    "phone": "",
    "addressFull": "2201 23rd St. NE Willmar, MN 56201 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/kandiyohi-county-jail",
    "latitude": 45.1457492,
    "longitude": -95.0139765
  },
  {
    "name": "Ozark County Jail",
    "fieldOffice": "Chicago Field Office",
    "address": "1818 County Road 806",
    "city": "Gainesville",
    "state": "MO",
    "postalCode": "65655",
    "country": "United States",
    "phone": "",
    "addressFull": "1818 County Road 806 Gainesville, MO 65655 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/ozark-county-jail",
    "latitude": 36.6032101,
    "longitude": -92.4596506
  },
  {
    "name": "Phelps County Jail",
    "fieldOffice": "Chicago Field Office",
    "address": "500 W. 2nd Street",
    "city": "Rolla",
    "state": "MO",
    "postalCode": "65401",
    "country": "United States",
    "phone": "",
    "addressFull": "500 W. 2nd Street Rolla, MO 65401 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/phelps-county-jail-0",
    "latitude": 37.9457141,
    "longitude": -91.77505339999999
  },
  {
    "name": "Greene County Jail",
    "fieldOffice": "Chicago Field Office",
    "address": "1199 N Haseltine Road",
    "city": "Springfield",
    "state": "MO",
    "postalCode": "65802",
    "country": "United States",
    "phone": "(417) 868-4040",
    "addressFull": "1199 N Haseltine Road Springfield, MO 65802 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/greene-county-jail",
    "latitude": 37.224653,
    "longitude": -93.38618
  },
  {
    "name": "Ste. Genevieve County Detention Center",
    "fieldOffice": "Chicago Field Office",
    "address": "5 Basler Drive",
    "city": "Ste. Genevieve",
    "state": "MO",
    "postalCode": "63670",
    "country": "United States",
    "phone": "",
    "addressFull": "5 Basler Drive Ste. Genevieve, MO 63670 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/ste-genevieve-county-detention-center",
    "latitude": 37.9653281,
    "longitude": -90.0557269
  },
  {
    "name": "CNMI Department of Corrections",
    "fieldOffice": "San Francisco Field Office",
    "address": "Vincente Taman Building",
    "city": "Susupe, Saipan",
    "state": "MP",
    "postalCode": "96950",
    "country": "United States",
    "phone": "",
    "addressFull": "Vincente Taman Building Susupe, Saipan, MP 96950 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/cnmi-department-corrections",
    "latitude": 15.1567839,
    "longitude": 145.7028775
  },
  {
    "name": "Adams County Correctional Center",
    "fieldOffice": "New Orleans Field Office",
    "address": "20 Hobo Forks Road",
    "city": "Natchez",
    "state": "MS",
    "postalCode": "39120",
    "country": "United States",
    "phone": "",
    "addressFull": "20 Hobo Forks Road Natchez, MS 39120 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/adams-county-detention-center",
    "latitude": 31.5574938,
    "longitude": -91.2217027
  },
  {
    "name": "Alamance County Detention Center",
    "fieldOffice": "Atlanta Field Office",
    "address": "109 South Maple Street",
    "city": "Graham",
    "state": "NC",
    "postalCode": "27253",
    "country": "United States",
    "phone": "",
    "addressFull": "109 South Maple Street Graham, NC 27253 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/alamance-county-detention-center",
    "latitude": 36.0683261,
    "longitude": -79.40356709999999
  },
  {
    "name": "Grand Forks County Correctional Center",
    "fieldOffice": "St. Paul Field Office",
    "address": "1701 North Washington",
    "city": "Grand Forks",
    "state": "ND",
    "postalCode": "58203",
    "country": "United States",
    "phone": "",
    "addressFull": "1701 North Washington Grand Forks, ND 58203 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/grand-forks-county-correctional-center",
    "latitude": 47.935621,
    "longitude": -97.0576258
  },
  {
    "name": "Phelps County Jail",
    "fieldOffice": "St. Paul Field Office",
    "address": "715 5th Avenue",
    "city": "Holdrege",
    "state": "NE",
    "postalCode": "68949",
    "country": "United States",
    "phone": "",
    "addressFull": "715 5th Avenue Holdrege, NE 68949 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/phelps-county-jail",
    "latitude": 40.4395445,
    "longitude": -99.3703646
  },
  {
    "name": "McCook Detention Center",
    "fieldOffice": "St. Paul Field Office",
    "address": "2309 US-83 N",
    "city": "McCook",
    "state": "NE",
    "postalCode": "69001",
    "country": "United States",
    "phone": "",
    "addressFull": "2309 US-83 N McCook, NE 69001 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/mccook-detention-center",
    "latitude": 40.2279917,
    "longitude": -100.6487162
  },
  {
    "name": "Federal Correctional Institution - Berlin, NH",
    "fieldOffice": "Boston Field Office",
    "address": "1 Success Loop Rd",
    "city": "Berlin",
    "state": "NH",
    "postalCode": "03570",
    "country": "United States",
    "phone": "",
    "addressFull": "1 Success Loop Rd Berlin, NH 03570 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/federal-correctional-institution-berlin-nh",
    "latitude": 44.5213005,
    "longitude": -71.1360472
  },
  {
    "name": "Strafford County Corrections",
    "fieldOffice": "Boston Field Office",
    "address": "266 County Farm Road",
    "city": "Dover",
    "state": "NH",
    "postalCode": "03820",
    "country": "United States",
    "phone": "",
    "addressFull": "266 County Farm Road Dover, NH 03820 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/strafford-county-corrections",
    "latitude": 43.218151,
    "longitude": -70.9400658
  },
  {
    "name": "Elizabeth Contract Detention Facility",
    "fieldOffice": "Newark Field Office",
    "address": "625 Evans Street",
    "city": "Elizabeth",
    "state": "NJ",
    "postalCode": "07201",
    "country": "United States",
    "phone": "",
    "addressFull": "625 Evans Street Elizabeth, NJ 07201 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/elizabeth-contract-detention-facility",
    "latitude": 40.6660324,
    "longitude": -74.1898667
  },
  {
    "name": "Delaney Hall Detention Facility",
    "fieldOffice": "Newark Field Office",
    "address": "451 Doremus Avenue",
    "city": "Newark",
    "state": "NJ",
    "postalCode": "07105",
    "country": "United States",
    "phone": "",
    "addressFull": "451 Doremus Avenue Newark, NJ 07105 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/delaney-hall-detention-facility",
    "latitude": 40.7181313,
    "longitude": -74.12849729999999
  },
  {
    "name": "Otero County Processing Center",
    "fieldOffice": "El Paso Field Office",
    "address": "26 McGregor Range Road",
    "city": "Chaparral",
    "state": "NM",
    "postalCode": "88081",
    "country": "United States",
    "phone": "",
    "addressFull": "26 McGregor Range Road Chaparral, NM 88081 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/otero-county-processing-center",
    "latitude": 32.0768294,
    "longitude": -106.2549005
  },
  {
    "name": "Torrance County Detention Facility",
    "fieldOffice": "El Paso Field Office",
    "address": "209 County Road A049",
    "city": "Estancia",
    "state": "NM",
    "postalCode": "87016",
    "country": "United States",
    "phone": "",
    "addressFull": "209 County Road A049 Estancia, NM 87016 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/torrance-county-detention-facility",
    "latitude": 34.7672813,
    "longitude": -106.0185814
  },
  {
    "name": "Cibola County Correctional Center",
    "fieldOffice": "El Paso Field Office",
    "address": "2000 Cibola Loop",
    "city": "Milan",
    "state": "NM",
    "postalCode": "87021",
    "country": "United States",
    "phone": "",
    "addressFull": "2000 Cibola Loop Milan, NM 87021 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/cibola-county-correctional-center",
    "latitude": 35.1799003,
    "longitude": -107.907208
  },
  {
    "name": "Henderson Detention Center",
    "fieldOffice": "Salt Lake City Field Office",
    "address": "18 E. Basic Road",
    "city": "Henderson",
    "state": "NV",
    "postalCode": "89015",
    "country": "United States",
    "phone": "",
    "addressFull": "18 E. Basic Road Henderson, NV 89015 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/henderson-detention-center",
    "latitude": 36.0309509,
    "longitude": -114.9787348
  },
  {
    "name": "Nevada Southern Detention Center",
    "fieldOffice": "Salt Lake City Field Office",
    "address": "2190 E Mesquite Avenue",
    "city": "Pahrump",
    "state": "NV",
    "postalCode": "89048",
    "country": "United States",
    "phone": "",
    "addressFull": "2190 E Mesquite Avenue Pahrump, NV 89048 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/nevada-southern-detention-center",
    "latitude": 36.252992,
    "longitude": -115.975308
  },
  {
    "name": "Washoe County Jail",
    "fieldOffice": "Salt Lake City Field Office",
    "address": "911 E Parr Blvd",
    "city": "Reno",
    "state": "NV",
    "postalCode": "89512",
    "country": "United States",
    "phone": "",
    "addressFull": "911 E Parr Blvd Reno, NV 89512 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/washoe-county-jail",
    "latitude": 39.573637,
    "longitude": -119.8109942
  },
  {
    "name": "Buffalo (Batavia) Service Processing Center",
    "fieldOffice": "Buffalo Field Office",
    "address": "4250 Federal Drive",
    "city": "Batavia",
    "state": "NY",
    "postalCode": "14020",
    "country": "United States",
    "phone": "",
    "addressFull": "4250 Federal Drive Batavia, NY 14020 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/buffalo-batavia-service-processing-center",
    "latitude": 43.0201451,
    "longitude": -78.2023932
  },
  {
    "name": "Broome County Correctional Facility",
    "fieldOffice": "Buffalo Field Office",
    "address": "155 Lt. VanWinkle Drive",
    "city": "Binghamton",
    "state": "NY",
    "postalCode": "13905",
    "country": "United States",
    "phone": "",
    "addressFull": "155 Lt. VanWinkle Drive Binghamton, NY 13905 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/broome-county-correctional-facility",
    "latitude": 42.1323993,
    "longitude": -75.9167679
  },
  {
    "name": "MDC Brooklyn",
    "fieldOffice": "New York City Field Office",
    "address": "80 29th Street",
    "city": "Brooklyn",
    "state": "NY",
    "postalCode": "11232",
    "country": "United States",
    "phone": "",
    "addressFull": "80 29th Street Brooklyn, NY 11232 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/mdc-brooklyn",
    "latitude": 40.6599299,
    "longitude": -74.0037546
  },
  {
    "name": "Orange County Jail",
    "fieldOffice": "New York City Field Office",
    "address": "110 Wells Farm Road",
    "city": "Goshen",
    "state": "NY",
    "postalCode": "10924",
    "country": "United States",
    "phone": "",
    "addressFull": "110 Wells Farm Road Goshen, NY 10924 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/orange-county-jail",
    "latitude": 41.4049515,
    "longitude": -74.35929720000001
  },
  {
    "name": "Clinton County Jail",
    "fieldOffice": "Buffalo Field Office",
    "address": "25 McCarthy Drive",
    "city": "Plattsburgh",
    "state": "NY",
    "postalCode": "12901",
    "country": "United States",
    "phone": "",
    "addressFull": "25 McCarthy Drive Plattsburgh, NY 12901 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/clinton-county-jail",
    "latitude": 44.72054319999999,
    "longitude": -73.4670063
  },
  {
    "name": "Geauga County Safety Center",
    "fieldOffice": "Detroit Field Office",
    "address": "12450 Merritt Road",
    "city": "Chardon",
    "state": "OH",
    "postalCode": "44024",
    "country": "United States",
    "phone": "",
    "addressFull": "12450 Merritt Road Chardon, OH 44024 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/geauga-county-safety-center",
    "latitude": 41.5046752,
    "longitude": -81.1915623
  },
  {
    "name": "Butler County Sheriff’s Office",
    "fieldOffice": "Detroit Field Office",
    "address": "705 Hanover Street",
    "city": "Hamilton",
    "state": "OH",
    "postalCode": "45011",
    "country": "United States",
    "phone": "",
    "addressFull": "705 Hanover Street Hamilton, OH 45011 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/butler-county-sheriffs-office",
    "latitude": 39.3875859,
    "longitude": -84.5557427
  },
  {
    "name": "Corrections Center of Northwest Ohio (CCNO)",
    "fieldOffice": "Detroit Field Office",
    "address": "03151 Co. Rd. 24.2",
    "city": "Stryker",
    "state": "OH",
    "postalCode": "43557",
    "country": "United States",
    "phone": "",
    "addressFull": "03151 Co. Rd. 24.2 Stryker, OH 43557 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/corrections-center-northwest-ohio-ccno",
    "latitude": 41.4852471,
    "longitude": -84.4598111
  },
  {
    "name": "Seneca County Jail",
    "fieldOffice": "Detroit Field Office",
    "address": "3040 South State Route 100",
    "city": "Tiffin",
    "state": "OH",
    "postalCode": "44883",
    "country": "United States",
    "phone": "",
    "addressFull": "3040 South State Route 100 Tiffin, OH 44883 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/seneca-county-jail",
    "latitude": 41.0793527,
    "longitude": -83.1538747
  },
  {
    "name": "Mahoning County Justice Center",
    "fieldOffice": "Detroit Field Office",
    "address": "110 Fifth Avenue",
    "city": "Youngstown",
    "state": "OH",
    "postalCode": "44503",
    "country": "United States",
    "phone": "",
    "addressFull": "110 Fifth Avenue Youngstown, OH 44503 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/mahoning-county-justice-center",
    "latitude": 41.1042306,
    "longitude": -80.6549256
  },
  {
    "name": "Northeast Ohio Correctional Center",
    "fieldOffice": "Detroit Field Office",
    "address": "2240 Hubbard Road",
    "city": "Youngstown",
    "state": "OH",
    "postalCode": "44505",
    "country": "United States",
    "phone": "",
    "addressFull": "2240 Hubbard Road Youngstown, OH 44505 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/northeast-ohio-correctional-center",
    "latitude": 41.13167869999999,
    "longitude": -80.63199780000001
  },
  {
    "name": "Cimarron Correctional Facility",
    "fieldOffice": "Dallas Field Office",
    "address": "3200 S. Kings Hwy",
    "city": "Cushing",
    "state": "OK",
    "postalCode": "74023",
    "country": "United States",
    "phone": "",
    "addressFull": "3200 S. Kings Hwy Cushing, OK 74023 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/cimarron-correctional-facility",
    "latitude": 35.9434371,
    "longitude": -96.7821932
  },
  {
    "name": "Kay County Detention Center",
    "fieldOffice": "Chicago Field Office",
    "address": "1101 West Dry Road",
    "city": "Newkirk",
    "state": "OK",
    "postalCode": "74647",
    "country": "United States",
    "phone": "",
    "addressFull": "1101 West Dry Road Newkirk, OK 74647 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/kay-county-detention-center",
    "latitude": 36.8678591,
    "longitude": -97.0691621
  },
  {
    "name": "Pike County Correctional Facility",
    "fieldOffice": "Philadelphia Field Office",
    "address": "175 Pike County Blvd.",
    "city": "Lords Valley",
    "state": "PA",
    "postalCode": "18428",
    "country": "United States",
    "phone": "",
    "addressFull": "175 Pike County Blvd. Lords Valley, PA 18428 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/pike-county-correctional-facility",
    "latitude": 41.3890147,
    "longitude": -75.0713413
  },
  {
    "name": "Clinton County Correctional Facility",
    "fieldOffice": "Philadelphia Field Office",
    "address": "58 Pine Mountain Road",
    "city": "McElhattan",
    "state": "PA",
    "postalCode": "17748",
    "country": "United States",
    "phone": "",
    "addressFull": "58 Pine Mountain Road McElhattan, PA 17748 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/clinton-county-correctional-facility",
    "latitude": 41.1508791,
    "longitude": -77.3499399
  },
  {
    "name": "FDC Philadelphia",
    "fieldOffice": "Philadelphia Field Office",
    "address": "700 Arch Street",
    "city": "Philadelphia",
    "state": "PA",
    "postalCode": "19106",
    "country": "United States",
    "phone": "",
    "addressFull": "700 Arch Street Philadelphia, PA 19106 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/fdc-philadelphia",
    "latitude": 39.9526835,
    "longitude": -75.1521168
  },
  {
    "name": "Moshannon Valley Processing Center",
    "fieldOffice": "Philadelphia Field Office",
    "address": "555 GEO Drive",
    "city": "Philipsburg",
    "state": "PA",
    "postalCode": "16866",
    "country": "United States",
    "phone": "",
    "addressFull": "555 GEO Drive Philipsburg, PA 16866 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/moshannon-valley-processing-center",
    "latitude": 40.9221524,
    "longitude": -78.2405572
  },
  {
    "name": "Wyatt Detention Facility",
    "fieldOffice": "Boston Field Office",
    "address": "950 High Street",
    "city": "Central Falls",
    "state": "RI",
    "postalCode": "02863",
    "country": "United States",
    "phone": "",
    "addressFull": "950 High Street Central Falls, RI 02863 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/wyatt-detention-facility",
    "latitude": 41.8924645,
    "longitude": -71.38395899999999
  },
  {
    "name": "Pennington County Jail",
    "fieldOffice": "St. Paul Field Office",
    "address": "307 Saint Joseph St",
    "city": "Rapid City",
    "state": "SD",
    "postalCode": "57701",
    "country": "United States",
    "phone": "",
    "addressFull": "307 Saint Joseph St Rapid City, SD 57701 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/pennington-county-jail",
    "latitude": 44.07868029999999,
    "longitude": -103.221535
  },
  {
    "name": "West Tennessee Detention Facility",
    "fieldOffice": "New Orleans Field Office",
    "address": "6299 Finde Naifeh Drive",
    "city": "Mason",
    "state": "TN",
    "postalCode": "38049",
    "country": "United States",
    "phone": "",
    "addressFull": "6299 Finde Naifeh Drive Mason, TN 38049 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/west-tennessee-detention-facility",
    "latitude": 35.4074582,
    "longitude": -89.5486122
  },
  {
    "name": "Prairieland Detention Facility",
    "fieldOffice": "Dallas Field Office",
    "address": "1209 Sunflower Lane",
    "city": "Alvarado",
    "state": "TX",
    "postalCode": "76009",
    "country": "United States",
    "phone": "",
    "addressFull": "1209 Sunflower Lane Alvarado, TX 76009 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/prairieland-detention-facility",
    "latitude": 32.4214133,
    "longitude": -97.19582779999999
  },
  {
    "name": "Bluebonnet Detention Facility",
    "fieldOffice": "Dallas Field Office",
    "address": "400 2nd Street",
    "city": "Anson",
    "state": "TX",
    "postalCode": "79501",
    "country": "United States",
    "phone": "",
    "addressFull": "400 2nd Street Anson, TX 79501 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/bluebonnet-detention-facility",
    "latitude": 32.7676451,
    "longitude": -99.8880841
  },
  {
    "name": "Joe Corley Processing Center",
    "fieldOffice": "Houston Field Office",
    "address": "500 Hilbig Road",
    "city": "Conroe",
    "state": "TX",
    "postalCode": "77301",
    "country": "United States",
    "phone": "",
    "addressFull": "500 Hilbig Road Conroe, TX 77301 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/joe-corley-processing-center",
    "latitude": 30.3357896,
    "longitude": -95.4480609
  },
  {
    "name": "Montgomery Processing Center",
    "fieldOffice": "Houston Field Office",
    "address": "806 Hilbig Road",
    "city": "Conroe",
    "state": "TX",
    "postalCode": "77301",
    "country": "United States",
    "phone": "",
    "addressFull": "806 Hilbig Road Conroe, TX 77301 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/montgomery-processing-center",
    "latitude": 30.336088,
    "longitude": -95.44250459999999
  },
  {
    "name": "Dilley Immigration Processing Center",
    "fieldOffice": "San Antonio Field Office",
    "address": "300 El Rancho Way",
    "city": "Dilley",
    "state": "TX",
    "postalCode": "78017",
    "country": "United States",
    "phone": "",
    "addressFull": "300 El Rancho Way Dilley, TX 78017 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/dilley-immigration-processing-center",
    "latitude": 28.6578745,
    "longitude": -99.2003862
  },
  {
    "name": "Eden Detention Center",
    "fieldOffice": "Dallas Field Office",
    "address": "704 E Broadway Street",
    "city": "Eden",
    "state": "TX",
    "postalCode": "76837",
    "country": "United States",
    "phone": "",
    "addressFull": "704 E Broadway Street Eden, TX 76837 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/eden-detention-center",
    "latitude": 31.2168095,
    "longitude": -99.8337901
  },
  {
    "name": "ERO El Paso Camp East Montana",
    "fieldOffice": "El Paso Field Office",
    "address": "6920 Digital Road",
    "city": "El Paso",
    "state": "TX",
    "postalCode": "79936",
    "country": "United States",
    "phone": "",
    "addressFull": "6920 Digital Road El Paso, TX 79936 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/camp-east-montana",
    "latitude": 31.811927,
    "longitude": -106.2981181
  },
  {
    "name": "El Paso Service Processing Center",
    "fieldOffice": "El Paso Field Office",
    "address": "8915 Montana Avenue",
    "city": "El Paso",
    "state": "TX",
    "postalCode": "79925",
    "country": "United States",
    "phone": "",
    "addressFull": "8915 Montana Avenue El Paso, TX 79925 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/el-paso-service-processing-center",
    "latitude": 31.7942381,
    "longitude": -106.3676273
  },
  {
    "name": "La Salle County Regional Detention Center",
    "fieldOffice": "San Antonio Field Office",
    "address": "832 East Texas HWY 44",
    "city": "Encinal",
    "state": "TX",
    "postalCode": "78019",
    "country": "United States",
    "phone": "",
    "addressFull": "832 East Texas HWY 44 Encinal, TX 78019 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/la-salle-county-regional-detention-center",
    "latitude": 28.0455037,
    "longitude": -99.3362626
  },
  {
    "name": "Limestone County Detention Center",
    "fieldOffice": "Houston Field Office",
    "address": "910 North Tyus Street",
    "city": "Groesbeck",
    "state": "TX",
    "postalCode": "76642",
    "country": "United States",
    "phone": "",
    "addressFull": "910 North Tyus Street Groesbeck, TX 76642 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/limestone-county-detention-center",
    "latitude": 31.5268364,
    "longitude": -96.51481919999999
  },
  {
    "name": "Rolling Plains Detention Center",
    "fieldOffice": "Dallas Field Office",
    "address": "118 County Road 206",
    "city": "Haskell",
    "state": "TX",
    "postalCode": "79521",
    "country": "United States",
    "phone": "",
    "addressFull": "118 County Road 206 Haskell, TX 79521 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/rolling-plains-detention-center",
    "latitude": 33.1771862,
    "longitude": -99.7217295
  },
  {
    "name": "Houston Contract Detention Facility",
    "fieldOffice": "Houston Field Office",
    "address": "15850 Export Plaza Drive",
    "city": "Houston",
    "state": "TX",
    "postalCode": "77032",
    "country": "United States",
    "phone": "",
    "addressFull": "15850 Export Plaza Drive Houston, TX 77032 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/houston-contract-detention-facility",
    "latitude": 29.9497807,
    "longitude": -95.31226939999999
  },
  {
    "name": "Karnes County Immigration Processing Center",
    "fieldOffice": "San Antonio Field Office",
    "address": "409 FM 1144",
    "city": "Karnes City",
    "state": "TX",
    "postalCode": "78118",
    "country": "United States",
    "phone": "",
    "addressFull": "409 FM 1144 Karnes City, TX 78118 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/karnes-county-ipc",
    "latitude": 28.8849772,
    "longitude": -97.9008355
  },
  {
    "name": "East Hidalgo Detention Center",
    "fieldOffice": "Harlingen Field Office",
    "address": "1300 E Hwy 107",
    "city": "La Villa",
    "state": "TX",
    "postalCode": "78562",
    "country": "United States",
    "phone": "",
    "addressFull": "1300 E Hwy 107 La Villa, TX 78562 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/east-hidalgo-detention-center",
    "latitude": 26.2963533,
    "longitude": -97.9178948
  },
  {
    "name": "CoreCivic Laredo Processing Center",
    "fieldOffice": "Harlingen Field Office",
    "address": "4702 East Saunders",
    "city": "Laredo",
    "state": "TX",
    "postalCode": "78401",
    "country": "United States",
    "phone": "",
    "addressFull": "4702 East Saunders Laredo, TX 78401 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/laredo-detention-center",
    "latitude": 27.5292214,
    "longitude": -99.44793399999999
  },
  {
    "name": "CoreCivic Webb County Detention Center",
    "fieldOffice": "Harlingen Field Office",
    "address": "9998 S. Highway 83",
    "city": "Laredo",
    "state": "TX",
    "postalCode": "78046",
    "country": "United States",
    "phone": "",
    "addressFull": "9998 S. Highway 83 Laredo, TX 78046 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/webb-county-detention-center",
    "latitude": 27.3698802,
    "longitude": -99.49025619999999
  },
  {
    "name": "Rio Grande Processing Center",
    "fieldOffice": "Harlingen Field Office",
    "address": "1001 San Rio Blvd",
    "city": "Laredo",
    "state": "TX",
    "postalCode": "78046",
    "country": "United States",
    "phone": "",
    "addressFull": "1001 San Rio Blvd Laredo, TX 78046 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/rio-grande-detention-center",
    "latitude": 27.377685,
    "longitude": -99.4901498
  },
  {
    "name": "IAH Polk Adult Detention Facility",
    "fieldOffice": "Houston Field Office",
    "address": "3400 FM 350 South",
    "city": "Livingston",
    "state": "TX",
    "postalCode": "77351",
    "country": "United States",
    "phone": "",
    "addressFull": "3400 FM 350 South Livingston, TX 77351 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/iah-polk-adult-detention-facility",
    "latitude": 30.6980352,
    "longitude": -95.0062201
  },
  {
    "name": "Port Isabel Service Processing Center",
    "fieldOffice": "Harlingen Field Office",
    "address": "27991 Buena Vista Blvd.",
    "city": "Los Fresnos",
    "state": "TX",
    "postalCode": "78566",
    "country": "United States",
    "phone": "",
    "addressFull": "27991 Buena Vista Blvd. Los Fresnos, TX 78566 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/port-isabel-service-processing-center",
    "latitude": 26.1569011,
    "longitude": -97.35055609999999
  },
  {
    "name": "South Texas ICE Processing Center",
    "fieldOffice": "San Antonio Field Office",
    "address": "566 Veterans Drive",
    "city": "Pearsall",
    "state": "TX",
    "postalCode": "78061",
    "country": "United States",
    "phone": "",
    "addressFull": "566 Veterans Drive Pearsall, TX 78061 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/south-texas-ice-processing-center",
    "latitude": 28.8973835,
    "longitude": -99.1187908
  },
  {
    "name": "El Valle Detention Facility",
    "fieldOffice": "Harlingen Field Office",
    "address": "1800 Industrial Drive",
    "city": "Raymondville",
    "state": "TX",
    "postalCode": "78580",
    "country": "United States",
    "phone": "",
    "addressFull": "1800 Industrial Drive Raymondville, TX 78580 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/el-valle-detention-facility",
    "latitude": 26.470298,
    "longitude": -97.7586475
  },
  {
    "name": "Coastal Bend Detention Center",
    "fieldOffice": "Harlingen Field Office",
    "address": "4909 Farm to Market Road",
    "city": "Robstown",
    "state": "TX",
    "postalCode": "78380",
    "country": "United States",
    "phone": "",
    "addressFull": "4909 Farm to Market Road Robstown, TX 78380 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/coastal-bend-detention-center",
    "latitude": 27.7903032,
    "longitude": -97.6688843
  },
  {
    "name": "T. Don Hutto Detention Center",
    "fieldOffice": "San Antonio Field Office",
    "address": "1001 Welch Street",
    "city": "Taylor",
    "state": "TX",
    "postalCode": "76574",
    "country": "United States",
    "phone": "",
    "addressFull": "1001 Welch Street Taylor, TX 76574 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/t-don-hutto-detention-center",
    "latitude": 30.5655231,
    "longitude": -97.4198336
  },
  {
    "name": "Caroline Detention Facility",
    "fieldOffice": "Washington Field Office",
    "address": "11093 SW Lewis Memorial Dr",
    "city": "Bowling Green",
    "state": "VA",
    "postalCode": "22427",
    "country": "United States",
    "phone": "",
    "addressFull": "11093 SW Lewis Memorial Dr Bowling Green, VA 22427 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/caroline-detention-facility",
    "latitude": 38.1116967,
    "longitude": -77.26721069999999
  },
  {
    "name": "Abyon | Farmville Detention Center",
    "fieldOffice": "Washington Field Office",
    "address": "508 Waterworks Road",
    "city": "Farmville",
    "state": "VA",
    "postalCode": "23901",
    "country": "United States",
    "phone": "",
    "addressFull": "508 Waterworks Road Farmville, VA 23901 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/farmville-detention-center",
    "latitude": 37.32044399999999,
    "longitude": -78.44087569999999
  },
  {
    "name": "Northwest ICE Processing Center (NWIPC)",
    "fieldOffice": "Seattle Field Office",
    "address": "1623 E J Street, Suite 2",
    "city": "Tacoma",
    "state": "WA",
    "postalCode": "98421-1615",
    "country": "United States",
    "phone": "",
    "addressFull": "1623 E J Street, Suite 2 Tacoma, WA 98421-1615 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/northwest-ice-processing-center-nwipc",
    "latitude": 47.24986029999999,
    "longitude": -122.4218964
  },
  {
    "name": "Dodge Detention Facility",
    "fieldOffice": "Chicago Field Office",
    "address": "216 W. Center Street",
    "city": "Juneau",
    "state": "WI",
    "postalCode": "53039",
    "country": "United States",
    "phone": "",
    "addressFull": "216 W. Center Street Juneau, WI 53039 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/dodge-detention-facility",
    "latitude": 43.4073522,
    "longitude": -88.706355
  },
  {
    "name": "Natrona County Detention Center",
    "fieldOffice": "Denver Field Office",
    "address": "1100 Bruce Lane",
    "city": "Casper",
    "state": "WY",
    "postalCode": "82601",
    "country": "United States",
    "phone": "",
    "addressFull": "1100 Bruce Lane Casper, WY 82601 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/natrona-county-detention-center",
    "latitude": 42.8626014,
    "longitude": -106.3455262
  },
  {
    "name": "Sweetwater County Detention Center",
    "fieldOffice": "Denver Field Office",
    "address": "50140 US Highway 191 South",
    "city": "Rock Springs",
    "state": "WY",
    "postalCode": "82901",
    "country": "United States",
    "phone": "",
    "addressFull": "50140 US Highway 191 South Rock Springs, WY 82901 United States",
    "detailUrl": "https://www.ice.gov/detain/detention-facilities/sweetwater-county-detention-center",
    "latitude": 41.5386685,
    "longitude": -109.302023
  }
] as const;
